version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: new_employee_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5422:5432"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "3422:3422"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: new_employee_db
      DB_PASSWORD: admin123
      DB_PORT: 5432
      PORT: 3422
      FRONTEND_URL: http://44.223.23.145:8043

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "8043:80"
    depends_on:
      - backend

  hr_page:
    build:
      context: ./HR_page
      dockerfile: Dockerfile
    container_name: hr_container
    ports:
      - "8044:80"
    depends_on:
      - backend

volumes:
  pgdata:

